name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' ||  github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: install dependencies
        run: |
          pnpm install
          pnpm exec playwright install --with-deps

      - name: lint
        run: pnpm lint

      - name: test
        id: test
        run: |
          pnpm test
          pnpm test:pw

      - name: Capture test output
        if: ${{ failure() && steps.test.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: ./test-results

      - name: build
        run: pnpm build
